"""Universo curado de fondos UCITS (NO ETF) disponibles en Europa.

Criterio de inclusión:
- Vehículo UCITS (SICAV, FCP, OEIC, FI español). Nunca ETF/ETC/ETN.
- Clase minorista habitual en plataformas UE (MyInvestor, EBN, Renta 4, Self Bank…).
- Mejor en su clase o referente de la temática (track record, AUM, equipo, TER relativo).
- Cobertura amplia de temas, sin relleno mediocre.

TER = ongoing charges / gastos corrientes de la clase indicada (KID, aprox.).
`bic` 1-5 = convicción best-in-class cualitativa (equipo + proceso + consistencia).
"""

# Campos: ver _campos
_CAMPOS = (
    "id", "nombre", "isin", "yahoo", "gestora", "domicilio", "divisa",
    "clase_activo", "categoria", "tema", "estilo", "ter", "sri", "bic",
    "tesis",
)

_FILAS = [
    # ===================== MONETARIOS =====================
    ("dws-esg-mm-eur", "DWS ESG Euro Money Market", "LU0225880524", "0P0000CVXG",
     "DWS", "LU", "EUR", "monetario", "monetario_eur", "liquidez", "efectivo",
     0.11, 1, 5, "Uno de los TER más bajos en monetario EUR UCITS con sello ESG y escala."),
    ("pictet-stmm-eur", "Pictet Short-Term Money Market EUR P", "LU0128494191", "0P00000JBB",
     "Pictet", "LU", "EUR", "monetario", "monetario_eur", "liquidez", "efectivo",
     0.25, 1, 5, "Referencia institucional de MM EUR: calidad crediticia y preservación."),
    ("bnp-mm-eur", "BNP Paribas Euro Money Market Classic C", "LU0083138064", "0P00000RDQ",
     "BNP Paribas AM", "LU", "EUR", "monetario", "monetario_eur", "liquidez", "efectivo",
     0.49, 1, 4, "Monetario EUR clásico, amplio y fácil de contratar en banca privada UE."),
    ("amundi-cash-eur", "Amundi Cash EUR A", "FR0010109173", "0P00000QZ0",
     "Amundi", "FR", "EUR", "monetario", "monetario_eur", "liquidez", "efectivo",
     0.20, 1, 4, "Escala de Amundi en tesorería EUR; útil como colchón táctico."),
    ("fidelity-euro-cash", "Fidelity Euro Cash A-Acc-EUR", "LU0261953519", "0P0000A2K4",
     "Fidelity", "LU", "EUR", "monetario", "monetario_eur", "liquidez", "efectivo",
     0.45, 1, 3, "Tesorería Fidelity, complemento de liquidez en cuentas de fondos."),
    ("gs-euro-liq", "Goldman Sachs Euro Liquid Reserves Acc", "IE00B09TPT27", "0P00001N7S",
     "Goldman Sachs AM", "IE", "EUR", "monetario", "monetario_eur", "liquidez", "efectivo",
     0.20, 1, 4, "MM institucional GS, foco en LVNAV y contrapartidas de alta calidad."),
    ("jpm-eur-liq", "JPM EUR Liquidity LVNAV Cap EUR", "LU0103813639", "0P00000T2H",
     "J.P. Morgan AM", "LU", "EUR", "monetario", "monetario_eur", "liquidez", "efectivo",
     0.16, 1, 5, "Plataforma de liquidez JPM: tamaño, proceso y TER competitivo."),
    ("ics-euro-liq", "BlackRock ICS Euro Liquidity Core Acc", "IE00B3X8M898", "0P0000X1K9",
     "BlackRock", "IE", "EUR", "monetario", "monetario_eur", "liquidez", "efectivo",
     0.10, 1, 5, "El estándar institucional BlackRock ICS en efectivo EUR."),

    # ===================== RENTA FIJA =====================
    ("carmignac-securite", "Carmignac Sécurité A EUR Acc", "FR0010149120", "0P00000R1A",
     "Carmignac", "FR", "EUR", "renta_fija", "rf_corto_eur", "corto_flexible", "flexible",
     1.00, 3, 5, "El 'bono flexible corto' europeo por excelencia. Drawdowns contenidos."),
    ("pimco-income-e", "PIMCO GIS Income E EUR Hedged Acc", "IE00B7KFL990", "0P0000U6Y4",
     "PIMCO", "IE", "EUR", "renta_fija", "rf_flexible", "strategic_income", "flexible",
     1.19, 4, 5, "Mayor fondo de income del mundo. Multisector, cobertura EUR, motor de cupón."),
    ("pimco-dynbond", "PIMCO GIS Dynamic Bond E EUR Acc", "IE00B11XZ574", "0P0000M2Y1",
     "PIMCO", "IE", "EUR", "renta_fija", "rf_flexible", "unconstrained", "flexible",
     1.44, 4, 4, "Duración táctica global. Brilla cuando hay que rotar el riesgo de tipos."),
    ("pimco-global-bond", "PIMCO GIS Global Bond E EUR Hedged Acc", "IE00B11XZ681", "0P0000M2Y2",
     "PIMCO", "IE", "EUR", "renta_fija", "rf_flexible", "global_ig", "calidad",
     1.44, 3, 4, "Core de deuda global IG con la máquina de tipos de PIMCO, hedged a EUR."),
    ("pimco-euro-bond", "PIMCO GIS Euro Bond E EUR Acc", "IE00B11XZ467", "0P0000M2XZ",
     "PIMCO", "IE", "EUR", "renta_fija", "rf_euro_gov", "euro_gobierno", "calidad",
     0.94, 3, 4, "Gobierno + crédito euro con gestión activa de curva. TER razonable."),
    ("pimco-hy", "PIMCO GIS High Yield Bond E EUR Hedged Acc", "IE00B11XZB36", "0P0000M2Y5",
     "PIMCO", "IE", "EUR", "renta_fija", "rf_hy", "high_yield", "carry",
     1.69, 5, 4, "HY US/global con filtro de impago PIMCO. Para tramos de expansión."),
    ("mg-optimal", "M&G (Lux) Optimal Income A EUR", "LU1670724373", "0P0001B8WQ",
     "M&G", "LU", "EUR", "renta_fija", "rf_flexible", "strategic_income", "flexible",
     1.35, 4, 4, "Clásico de Richard Woolnough: asset allocation entre govies, IG y HY."),
    ("jupiter-dynbond", "Jupiter Dynamic Bond L EUR Acc", "LU0853555380", "0P0000Y6N4",
     "Jupiter", "LU", "EUR", "renta_fija", "rf_flexible", "unconstrained", "flexible",
     1.47, 4, 4, "Ariel Bezalel: duration extrema y crédito. Alta convicción, no es un indexado."),
    ("fvs-bond-opp", "Flossbach von Storch Bond Opportunities R", "LU0399027613", "0P0000J6QK",
     "Flossbach von Storch", "LU", "EUR", "renta_fija", "rf_flexible", "calidad_credito", "calidad",
     1.02, 3, 5, "Crédito de calidad con mentalidad de dueño. TER contenido para activo."),
    ("twentyfour-si", "Vontobel TwentyFour Strategic Income A EUR", "LU0966469252", "0P00013V2N",
     "Vontobel / TwentyFour", "LU", "EUR", "renta_fija", "rf_flexible", "strategic_income", "flexible",
     1.32, 4, 4, "ABS + crédito europeo. Muy útil como diversificador vs. govies."),
    ("nordea-ffi", "Nordea 1 Flexible Fixed Income BP EUR", "LU0173798793", "0P00009B2M",
     "Nordea", "LU", "EUR", "renta_fija", "rf_flexible", "unconstrained", "flexible",
     1.10, 3, 4, "Proceso cuant + fundamental nórdico. Correlación baja con RV en sustos."),
    ("allianz-euro-bond", "Allianz Euro Bond A EUR", "LU0165915215", "0P00000S6C",
     "Allianz GI", "LU", "EUR", "renta_fija", "rf_euro_gov", "euro_gobierno", "calidad",
     1.04, 3, 3, "Core euro duration. Pieza de recesión / risk-off."),
    ("robeco-euro-credit", "Robeco Euro Credit Bonds DH EUR", "LU0213098847", "0P0000C2Y8",
     "Robeco", "LU", "EUR", "renta_fija", "rf_euro_corp", "euro_ig", "calidad",
     0.89, 3, 4, "Crédito IG euro con factor credits. TER atractivo vs. peers activos."),
    ("bluebay-ig-euro", "BlueBay IG Euro Government Bond R EUR", "LU0549536712", "0P0000U2K1",
     "RBC BlueBay", "LU", "EUR", "renta_fija", "rf_euro_gov", "euro_gobierno", "calidad",
     0.80, 3, 4, "Gobierno euro puro de boutique de crédito. Útil como lastre defensivo."),
    ("candriam-hy-euro", "Candriam Bonds Euro High Yield C EUR Acc", "LU0012119607", "0P00000R8K",
     "Candriam", "LU", "EUR", "renta_fija", "rf_hy", "high_yield_euro", "carry",
     1.28, 5, 4, "HY europeo, menos energía US que el HY global. Mejor fit recesión europea suave."),
    ("muzinich-eyst", "Muzinich EnhancedYield Short-Term H EUR Acc", "IE00B65Z9D26", "0P0000W1K8",
     "Muzinich", "IE", "EUR", "renta_fija", "rf_corto_eur", "credito_corto", "carry",
     0.95, 3, 4, "Crédito corto global. Sustituto de monetario cuando el carry IG corto paga."),
    ("axa-inflation", "AXA WF Global Inflation Bonds A EUR Hdg", "LU0266009793", "0P0000C8N2",
     "AXA IM", "LU", "EUR", "renta_fija", "rf_inflation", "linkers", "defensivo",
     0.84, 4, 4, "Linkers globales. Pieza de inflación / stagflation."),
    ("templeton-gbonde", "Templeton Global Bond A EUR H1 Acc", "LU0294221160", "0P0000G2Y9",
     "Franklin Templeton", "LU", "EUR", "renta_fija", "rf_flexible", "global_macro_bond", "macro",
     1.40, 4, 3, "Macro de divisas + tipos. Alta tracking error: satélite, no core."),
    ("evli-short-cb", "Evli Short Corporate Bond B EUR", "FI4000233230", "0P0001B2K1",
     "Evli", "FI", "EUR", "renta_fija", "rf_corto_eur", "credito_corto", "calidad",
     0.55, 2, 5, "Boutique nórdica, crédito IG corto, TER bajo. Excelente ratio coste/riesgo."),
    ("dpam-eur-gov", "DPAM L Bonds EUR Government Sustainable A", "LU0135182147", "0P0000A2Y1",
     "DPAM", "LU", "EUR", "renta_fija", "rf_euro_gov", "euro_gobierno", "esg",
     0.60, 3, 4, "Gobierno euro con filtro sostenible. TER de los más bajos en activo."),
    ("man-hy-opp", "Man GLG High Yield Opportunities D EUR", "IE00BD352C76", "0P0001C2K9",
     "Man GLG", "IE", "EUR", "renta_fija", "rf_hy", "high_yield", "high_conviction",
     1.50, 5, 4, "HY de alta convicción. Para tramos de risk-on de crédito."),
    ("jpm-em-debt", "JPM Emerging Markets Debt A EUR Hdg", "LU0108415935", "0P00000T8M",
     "J.P. Morgan AM", "LU", "EUR", "renta_fija", "rf_em", "deuda_emergente", "carry",
     1.35, 5, 4, "Hard-currency EM debt de referencia. Satélite de carry en expansión."),
    ("pimco-lowdur-inc", "PIMCO GIS Low Duration Income E EUR Hdg Acc", "IE00BYXVWC37", "0P0001B9K2",
     "PIMCO", "IE", "EUR", "renta_fija", "rf_corto_eur", "income_corto", "carry",
     1.19, 3, 4, "Income con duración baja. Puente entre monetario y strategic income."),

    # ===================== MIXTOS / PATRIMONIO =====================
    ("carmignac-pat", "Carmignac Patrimoine A EUR Acc", "FR0010135103", "0P00000R19",
     "Carmignac", "FR", "EUR", "mixto", "mixto_flex", "patrimonio", "flexible",
     1.50, 4, 4, "El mixto flexible europeo original. Oro + RV + RF según régimen."),
    ("fvs-multiple", "Flossbach Multiple Opportunities R", "LU0323578657", "0P0000J6QH",
     "Flossbach von Storch", "LU", "EUR", "mixto", "mixto_flex", "calidad_multi", "calidad",
     1.62, 4, 5, "Calidad + oro físico vía ETC en cartera. Mentalidad de family office."),
    ("kaldemorgen", "DWS Concept Kaldemorgen LC", "LU0599947271", "0P0000X6N2",
     "DWS", "LU", "EUR", "mixto", "mixto_flex", "absoluto", "asimetrico",
     1.50, 4, 5, "Klaus Kaldemorgen: control de drawdown como objetivo, no el benchmark."),
    ("first-eagle", "First Eagle Amundi International AU-C", "LU0068456623", "0P00000R5N",
     "Amundi / First Eagle", "LU", "EUR", "mixto", "mixto_flex", "value_oro", "value",
     2.20, 5, 5, "Value global + oro. Históricamente el mejor 'all weather' de true value."),
    ("mfs-prudent", "MFS Meridian Prudent Wealth A1 EUR", "LU0094561056", "0P00000S8Q",
     "MFS", "LU", "EUR", "mixto", "mixto_mod", "prudente", "calidad",
     1.85, 4, 4, "Calidad + puts tácticos. Pensado para no perder el capital en bear markets."),
    ("nordea-stable", "Nordea 1 Stable Return BP EUR", "LU0227384020", "0P0000C7Y1",
     "Nordea", "LU", "EUR", "mixto", "mixto_mod", "estable", "cuantitativo",
     1.79, 4, 3, "Risk-parity nórdico. Diversificador, no un generador de alpha táctico."),
    ("bgf-allocation", "BGF Global Allocation A2 EUR", "LU0072462426", "0P00000R0K",
     "BlackRock", "LU", "EUR", "mixto", "mixto_flex", "global_allocation", "blend",
     1.77, 5, 3, "El GA de BlackRock: 3 motores (RV/RF/commodities) con escala enorme."),
    ("invesco-pehi", "Invesco Pan European High Income A EUR", "LU0243957239", "0P0000C8K1",
     "Invesco", "LU", "EUR", "mixto", "mixto_mod", "income_europa", "income",
     1.62, 4, 4, "Mixto europeo de cupón (HY + financieras + defensivas). Régimen late-cycle."),

    # ===================== RV GLOBAL / USA / EUROPA =====================
    ("fundsmith-sicav", "Fundsmith Equity Fund SICAV T EUR Acc", "LU0690375182", "0P0000Y1K4",
     "Fundsmith", "LU", "EUR", "renta_variable", "rv_global_growth", "calidad_global", "calidad",
     1.10, 5, 5, "Buy-and-hold de compañías 'unbreakable'. TER bajo para activo de calidad."),
    ("ms-global-opp", "MS INVF Global Opportunity A USD", "LU0552385295", "0P0000U6BB",
     "Morgan Stanley IM", "LU", "USD", "renta_variable", "rv_global_growth", "growth_global", "growth",
     1.83, 6, 5, "Kristian Heugh: growth concentrado de alta convicción. Convexo en bull markets."),
    ("cg-new-perspective", "Capital Group New Perspective (LUX) B EUR", "LU1295554833", "0P00016N2K",
     "Capital Group", "LU", "EUR", "renta_variable", "rv_global_blend", "global_core", "blend",
     1.59, 5, 5, "El NP desde 1973. Multi-counselor, core global difícil de batir a 10 años."),
    ("comgest-world", "Comgest Growth World EUR Acc", "LU0390221938", "0P0000J8K2",
     "Comgest", "LU", "EUR", "renta_variable", "rv_global_growth", "calidad_growth", "calidad",
     1.75, 5, 4, "Quality growth 'la francesa': pocos nombres, alta visibilidad de beneficios."),
    ("seilern-world", "Seilern World Growth EUR U R", "IE00B4KKPT62", "0P0000U8N1",
     "Seilern", "IE", "EUR", "renta_variable", "rv_global_growth", "calidad_global", "calidad",
     1.50, 5, 5, "Quality growth puro, concentrado, baja rotación. Uno de los mejores procesos."),
    ("mfs-global-eq", "MFS Meridian Global Equity A1 EUR", "LU0094560744", "0P00000S8P",
     "MFS", "LU", "EUR", "renta_variable", "rv_global_blend", "calidad_global", "calidad",
     1.82, 5, 4, "Calidad blend Boston. Menos drama que el growth puro, mejores DD."),
    ("guardcap-global", "GuardCap Global Equity USD I", "IE00B54VDR61", "0P0000Y4K8",
     "GuardCap", "IE", "USD", "renta_variable", "rv_global_growth", "calidad_global", "calidad",
     0.80, 5, 5, "Ex-Sands. Concentrado, TER de clase I. Best-in-class de quality global."),
    ("edgewood-us", "Edgewood L Select US Select Growth A USD", "LU0162517646", "0P00000S9N",
     "Edgewood", "LU", "USD", "renta_variable", "rv_usa_growth", "growth_usa", "growth",
     1.87, 6, 5, "Concentrado US growth (≈10-20 nombres). El 'high conviction' americano en UCITS."),
    ("polen-us", "Polen Capital Focus US Growth I USD", "IE00B80LQR57", "0P00012K9M",
     "Polen Capital", "IE", "USD", "renta_variable", "rv_usa_growth", "calidad_usa", "calidad",
     1.00, 6, 4, "US quality growth concentrado. Mejor TER que Edgewood retail."),
    ("brown-us-flex", "Brown Advisory US Flexible Equity B USD", "IE00B0MY6T00", "0P0000M8K2",
     "Brown Advisory", "IE", "USD", "renta_variable", "rv_usa_blend", "blend_usa", "blend",
     1.50, 5, 4, "Flexible US (growth/value táctico) de boutique de Baltimore."),
    ("trp-us-blue", "T. Rowe Price US Blue Chip Equity A USD", "LU0133084623", "0P00000T9K",
     "T. Rowe Price", "LU", "USD", "renta_variable", "rv_usa_growth", "bluechip_usa", "growth",
     1.67, 5, 4, "Blue chips US con research profundo TRP. Core growth USA."),
    ("comgest-europe", "Comgest Growth Europe EUR Acc", "IE0004766675", "0P00000M2K",
     "Comgest", "IE", "EUR", "renta_variable", "rv_europa", "calidad_europa", "calidad",
     1.50, 5, 5, "El quality europe de referencia. Décadas de compuesto con DD aceptable."),
    ("bgf-cef", "BGF Continental European Flexible A2 EUR", "LU0224105477", "0P0000C2N8",
     "BlackRock", "LU", "EUR", "renta_variable", "rv_europa", "flexible_europa", "blend",
     1.82, 6, 4, "Algebris? No: BGF CEF de Nigel Bolton. Flexible Europe, track largo."),
    ("jpm-eu-value", "JPM Europe Strategic Value A EUR Acc", "LU0107398884", "0P00000T5N",
     "J.P. Morgan AM", "LU", "EUR", "renta_variable", "rv_europa", "value_europa", "value",
     1.70, 6, 4, "Value europeo de JPM. Encaja en rotación value / late-cycle / recovery."),
    ("brandes-eu", "Brandes European Value A EUR", "IE0031574977", "0P00001N8K",
     "Brandes", "IE", "EUR", "renta_variable", "rv_europa", "value_europa", "value",
     1.85, 6, 4, "Deep value grahamite. Para cuando Europa cotiza a descuento estructural."),
    ("mg-eu-value", "M&G (Lux) European Strategic Value A EUR", "LU1670710174", "0P0001B8WP",
     "M&G", "LU", "EUR", "renta_variable", "rv_europa", "value_europa", "value",
     1.69, 6, 4, "Value europeo de M&G, buen complemento a Comgest quality."),
    ("azvalor-int", "azValor Internacional FI", "ES0112616000", "0P00013K9Q",
     "azValor", "ES", "EUR", "renta_variable", "rv_global_value", "value_global", "value",
     1.80, 6, 5, "Value ibérico de alta convicción (commodities, energía, minas). Asimétrico."),
    ("cobas-int", "Cobas Internacional FI", "ES0124037005", "0P00016N8K",
     "Cobas AM", "ES", "EUR", "renta_variable", "rv_global_value", "value_global", "value",
     1.75, 6, 4, "Paramés. Deep value global. Largos periodos de sequía y rachas potentes."),
    ("bestinver-int", "Bestinver Internacional FI", "ES0114673032", "0P00000QZ8",
     "Bestinver", "ES", "EUR", "renta_variable", "rv_global_value", "value_europa", "value",
     1.79, 6, 4, "Casa value española histórica. Más Europa que azValor, menos commodities."),
    ("magallanes-eu", "Magallanes European Equity FI", "ES0157323000", "0P00016N9M",
     "Magallanes", "ES", "EUR", "renta_variable", "rv_europa", "value_europa", "value",
     1.75, 6, 4, "Value europeo de Iván Martín. Proceso disciplinado, AUM contenido."),
    ("horos-int", "Horos Value Internacional FI", "ES0146598004", "0P0001C8K1",
     "Horos AM", "ES", "EUR", "renta_variable", "rv_global_value", "value_global", "value",
     1.50, 6, 3, "Value small/mid global. Satélite de azValor/Cobas con TER algo mejor."),
    ("true-value", "True Value FI", "ES0180792006", "0P00013K8N",
     "True Value", "ES", "EUR", "renta_variable", "rv_global_blend", "small_global", "blend",
     1.50, 6, 3, "Small/mid quality-value español. Diversificador de large caps globales."),

    # ===================== TEMÁTICOS / SECTORIALES =====================
    ("fidelity-gtec", "Fidelity Global Technology A-Acc-EUR", "LU0099574567", "0P00000R7Y",
     "Fidelity", "LU", "EUR", "renta_variable", "rv_tech", "tecnologia", "growth",
     1.92, 6, 5, "Hyun Ho Sohn. Uno de los mejores tech activos UCITS a 10 años."),
    ("bgf-wtech", "BGF World Technology A2 USD", "LU0171310443", "0P00000R0Q",
     "BlackRock", "LU", "USD", "renta_variable", "rv_tech", "tecnologia", "growth",
     1.81, 6, 4, "Tech global de BGF. Escala y acceso, TER típico de clase A."),
    ("allianz-ai", "Allianz Global Artificial Intelligence AT EUR", "LU1548499388", "0P00019N2K",
     "Allianz GI", "LU", "EUR", "renta_variable", "rv_tech", "inteligencia_artificial", "growth",
     2.05, 6, 4, "IA pura (semis, software, data). Satélite de régimen expansión/tech."),
    ("pictet-robotics", "Pictet Robotics P EUR", "LU1279334210", "0P00016N4R",
     "Pictet", "LU", "EUR", "renta_variable", "rv_tech", "robotica_ia", "growth",
     1.60, 6, 4, "Automatización + IA. Menos 'Magnificent 7 puro' que Allianz AI."),
    ("polar-tech", "Polar Capital Global Technology I USD", "IE00B42W4L06", "0P0000Y8K2",
     "Polar Capital", "IE", "USD", "renta_variable", "rv_tech", "tecnologia", "growth",
     1.15, 6, 5, "Boutique tech de primer nivel. TER de clase I, proceso diferenciado."),
    ("pictet-water", "Pictet Water P EUR", "LU0104884860", "0P00000R4W",
     "Pictet", "LU", "EUR", "renta_variable", "rv_clima", "agua", "calidad",
     1.60, 5, 5, "El fondo de agua de referencia mundial. Tema estructural, no cíclico."),
    ("pictet-security", "Pictet Security P EUR", "LU0270904781", "0P0000C8Y2",
     "Pictet", "LU", "EUR", "renta_variable", "rv_tech", "ciberseguridad", "calidad",
     1.60, 5, 4, "Security (cyber + defensa civil). Encaja en regímenes geopolíticos."),
    ("pictet-megatrend", "Pictet Global Megatrend Selection P EUR", "LU0386882277", "0P0000J8Y1",
     "Pictet", "LU", "EUR", "renta_variable", "rv_global_growth", "megatendencias", "growth",
     1.60, 5, 4, "Cesta de temáticos Pictet en un solo ISIN. Core temático."),
    ("robeco-consumer", "Robeco Global Consumer Trends D EUR", "LU0187079347", "0P0000C2Y9",
     "Robeco", "LU", "EUR", "renta_variable", "rv_global_growth", "consumo", "growth",
     1.71, 5, 4, "Consumo digital + lujo + salud. Calidad growth no-tech puro."),
    ("nordea-climate", "Nordea 1 Global Climate & Environment BP EUR", "LU0348926287", "0P0000J9K1",
     "Nordea", "LU", "EUR", "renta_variable", "rv_clima", "clima", "blend",
     1.83, 6, 4, "Transición energética de verdad (industriales, utilities, materiales)."),
    ("impax-env", "Impax Environmental Markets A EUR", "IE00BBP4SS44", "0P00015N2K",
     "Impax", "IE", "EUR", "renta_variable", "rv_clima", "medioambiente", "blend",
     1.80, 5, 5, "Pionero ambiental (2002). Menos 'hype solar', más compounders ambientales."),
    ("bgf-health", "BGF World Healthscience A2 USD", "LU0122379950", "0P00000R0P",
     "BlackRock", "LU", "USD", "renta_variable", "rv_salud", "salud", "blend",
     1.81, 5, 4, "Salud global líquido. Defensivo relativo en risk-off de growth."),
    ("candriam-onco", "Candriam Equities L Oncology C EUR Acc", "LU1864482324", "0P0001C9N2",
     "Candriam", "LU", "EUR", "renta_variable", "rv_salud", "oncologia", "growth",
     1.80, 6, 4, "Oncología pura. Satélite de innovación médica, alta idiosincrasia."),
    ("polar-health", "Polar Capital Healthcare Opportunities I EUR", "IE00B3N2H554", "0P0000Y8K3",
     "Polar Capital", "IE", "EUR", "renta_variable", "rv_salud", "salud", "blend",
     1.10, 6, 5, "Boutique healthcare. Mejor TER que las clases A de las grandes casas."),
    ("fidelity-health", "Fidelity Global Health Care A-Acc-EUR", "LU0114720955", "0P00000R7Z",
     "Fidelity", "LU", "EUR", "renta_variable", "rv_salud", "salud", "blend",
     1.92, 5, 3, "Salud Fidelity. Core sectorial, menos diferenciado que Polar."),
    ("first-sentier-infra", "First Sentier Global Listed Infrastructure B EUR", "IE00BZ4G5287", "0P0001B2N8",
     "First Sentier", "IE", "EUR", "renta_variable", "rv_infra", "infraestructuras", "value",
     1.60, 5, 5, "Infra cotizada de referencia. Inflación + dividendo + monopolios naturales."),
    ("mg-infra", "M&G (Lux) Global Listed Infrastructure A EUR", "LU1665237704", "0P0001B8WR",
     "M&G", "LU", "EUR", "renta_variable", "rv_infra", "infraestructuras", "blend",
     1.69, 5, 4, "Infra global M&G. Complemento a First Sentier."),
    ("cpr-disruptive", "CPR Invest Global Disruptive Opportunities A EUR", "LU1530899142", "0P00019N8K",
     "CPR / Amundi", "LU", "EUR", "renta_variable", "rv_tech", "disrupcion", "growth",
     2.00, 6, 3, "Disrupción amplia (fintech, biotech, energy). Satélite especulativo."),
    ("echiquier-weg", "Echiquier World Equity Growth A EUR", "FR0010859844", "0P0000Y2K1",
     "LFDE", "FR", "EUR", "renta_variable", "rv_global_growth", "growth_global", "growth",
     1.80, 5, 4, "Growth global francés de convicción. Alternativa a MS Opportunity."),
    ("carmignac-inv", "Carmignac Investissement A EUR Acc", "FR0010148981", "0P00000R18",
     "Carmignac", "FR", "EUR", "renta_variable", "rv_global_growth", "flexible_global", "flexible",
     1.50, 5, 4, "RV global flexible (hasta 100% RV) del equipo Patrimoine."),
    ("bgf-wdiv", "BGF Global Equity Income A2 EUR", "LU0582471473", "0P0000X8N2",
     "BlackRock", "LU", "EUR", "renta_variable", "rv_global_div", "dividendo_global", "income",
     1.82, 5, 3, "Dividendo global líquido. Pieza de late-cycle / need-for-income."),
    ("comgest-america", "Comgest Growth America EUR Acc", "IE0004765925", "0P00000M2L",
     "Comgest", "IE", "EUR", "renta_variable", "rv_usa_growth", "calidad_usa", "calidad",
     1.50, 5, 4, "Quality US a la Comgest. Menos FOMO tech, más compounders."),

    # ===================== GEOGRAFÍA: EM / ASIA / JAPÓN / INDIA / CHINA =====================
    ("comgest-magellan", "Comgest Magellan C", "FR0000292278", "0P00000QZ9",
     "Comgest", "FR", "EUR", "renta_variable", "rv_em", "emergentes_calidad", "calidad",
     1.70, 6, 5, "EM quality desde 1988. El anti-index EM: sin bancos basura ni cíclicos puros."),
    ("bgf-em", "BGF Emerging Markets A2 USD", "LU0047713382", "0P00000R0J",
     "BlackRock", "LU", "USD", "renta_variable", "rv_em", "emergentes", "blend",
     1.89, 6, 3, "EM core líquido. Para no quedarse sin beta emergente."),
    ("jpm-em-eq", "JPM Emerging Markets Equity A EUR Acc", "LU0217576759", "0P0000C2T1",
     "J.P. Morgan AM", "LU", "EUR", "renta_variable", "rv_em", "emergentes", "blend",
     1.80, 6, 4, "EM equity de JPM, research local. Mejor proceso que el BGF A2 típico."),
    ("schroder-asia", "Schroder ISF Asian Opportunities A Acc EUR", "LU0248183658", "0P0000C8N8",
     "Schroders", "LU", "EUR", "renta_variable", "rv_asia", "asia", "blend",
     1.71, 6, 4, "Asia ex-Japan de casa con músculo regional. Core Asia."),
    ("fidelity-china", "Fidelity China Consumer A-Acc-EUR", "LU0594300179", "0P0000X8K1",
     "Fidelity", "LU", "EUR", "renta_variable", "rv_asia", "china_consumo", "growth",
     1.92, 6, 4, "China consumo (no banks/SOE puro). Satélite geopolítico, alta volatilidad."),
    ("fidelity-india", "Fidelity India Focus A-Acc-EUR", "LU0261946448", "0P0000C8K8",
     "Fidelity", "LU", "EUR", "renta_variable", "rv_asia", "india", "growth",
     1.91, 6, 4, "India de Fidelity. Tema estructural demográfico / formalización."),
    ("gs-india", "Goldman Sachs India Equity A EUR Acc", "LU0234572450", "0P0000C8K9",
     "Goldman Sachs AM", "LU", "EUR", "renta_variable", "rv_asia", "india", "growth",
     1.85, 6, 4, "India GS. Alternativa a Fidelity con sesgo algo más large cap."),
    ("jpm-japan", "JPM Japan Equity A EUR Acc", "LU0210529223", "0P0000C2T2",
     "J.P. Morgan AM", "LU", "EUR", "renta_variable", "rv_japon", "japon", "blend",
     1.80, 6, 4, "Japón activo de JPM. Encaja con reforma de gobierno corporativo JP."),
    ("baillie-ltgg", "Baillie Gifford WW Long Term Global Growth B EUR", "IE00BD5K7Z23", "0P0001B3N1",
     "Baillie Gifford", "IE", "EUR", "renta_variable", "rv_global_growth", "growth_visionario", "growth",
     0.72, 6, 5, "LTGG: el growth más extremo (10-20 años). TER bajo. DD brutales, convexidad."),
    ("stewart-apac", "Stewart Investors Asia Pacific Leaders A EUR", "IE00BFY85M25", "0P0001B4K2",
     "Stewart Investors", "IE", "EUR", "renta_variable", "rv_asia", "asia_calidad", "calidad",
     1.70, 5, 5, "Calidad + stewardship en Asia. El anti-momentum asiático."),

    # ===================== ORO / MINERÍA =====================
    ("bgf-wgold", "BGF World Gold A2 USD", "LU0055631609", "0P00000R0N",
     "BlackRock", "LU", "USD", "oro", "oro_mineras", "oro_mineras", "ciclico",
     2.06, 6, 5, "El fondo de mineras de oro más grande UCITS. Beta oro × apalancamiento operativo."),
    ("bgf-wmining", "BGF World Mining A2 USD", "LU0075056555", "0P00000R0O",
     "BlackRock", "LU", "USD", "oro", "mineria", "mineria", "ciclico",
     2.07, 6, 4, "Minería diversificada (Cu, Au, Fe). Inflación real + ciclo industrial China."),
    ("bakersteel-pm", "Bakersteel Precious Metals B EUR", "LU0357130854", "0P0000J9N2",
     "Bakersteel", "LU", "EUR", "oro", "oro_mineras", "oro_mineras", "high_conviction",
     1.75, 6, 5, "Boutique de mineras. Históricamente mejor stock-picking que BGF World Gold."),
    ("ninety-gold", "Ninety One GSF Global Gold A Acc USD", "LU0345777009", "0P0000J9N3",
     "Ninety One", "LU", "USD", "oro", "oro_mineras", "oro_mineras", "blend",
     1.90, 6, 4, "Ex-Investec Global Gold. Proceso sólido, menos marketing que BGF."),
    ("earth-gold", "Earth Gold Fund UI", "DE000A0Q2XN3", "0P0000U9K1",
     "Universal-Investment", "DE", "EUR", "oro", "oro_mineras", "oro_mineras", "high_conviction",
     1.92, 6, 3, "Mineras mid-tier. Satélite de Bakersteel, más idiosincrático."),

    # ===================== SMALL CAP / OTROS =====================
    ("alger-small", "Alger Small Cap Focus I USD", "LU0345926622", "0P0000J9N4",
     "Alger", "LU", "USD", "renta_variable", "rv_usa_growth", "small_usa", "growth",
     1.85, 6, 4, "US small growth concentrado. Para early-cycle / recovery."),
    ("groupama-europe-s", "Groupama Europe Stock A", "FR0010288308", "0P00000R2K",
     "Groupama AM", "FR", "EUR", "renta_variable", "rv_europa", "europa_core", "blend",
     1.30, 5, 3, "Europa core con TER mejor que la media de clases A."),
]


assert all(len(f) == len(_CAMPOS) for f in _FILAS)


def universo() -> list[dict]:
    out = []
    for fila in _FILAS:
        d = dict(zip(_CAMPOS, fila))
        d["etf"] = False
        d["ucits"] = True
        d["ter"] = float(d["ter"])
        d["sri"] = int(d["sri"])
        d["bic"] = int(d["bic"])
        out.append(d)
    return out


def por_id() -> dict[str, dict]:
    return {f["id"]: f for f in universo()}
